/*
 * This source file was generated by the Gradle 'init' task
 */
package exercicio;

import java.util.Scanner;

import org.checkerframework.checker.units.qual.s;

import exercicio.model.Personagem;


public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);


        System.out.println("Digite o nome do personagem: ");
        String name = sc.next();
        System.out.println("Digite a cabeça do personagem: ");
        String setCabeça = sc.next();
        System.out.println("Digite a armadura do personagem: ");
        String setPeito = sc.next();
        System.out.println("Digite a arma do personagem: ");
        String arma = sc.next();

        Personagem prs = new Personagem(name, setCabeça, setPeito, arma);

        
    }
}